In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt #길지만 상세세팅 가능

#%matplotlib inline #짧지만 아예 specific하게 설정이 정해진 방식

#약간은 길지만 좀 더 상세 세팅이 가능한 방식
df = pd.read_csv('walmart_stock.csv')
df.head()
#data type 을 보면 date가 string 형식으로 import됨 -> resampling 불가

         Date       Open       High        Low      Close    Volume  Adj Close
0  2012-01-03  59.970001  61.060001  59.869999  60.330002  12668800  52.619235
1  2012-01-04  60.209999  60.349998  59.470001  59.709999   9593300  52.078475
2  2012-01-05  59.349998  59.619999  58.369999  59.419998  12768200  51.825539
3  2012-01-06  59.419998  59.450001  58.869999  59.000000   8069400  51.459220
4  2012-01-09  59.029999  59.549999  58.919998  59.180000   6679300  51.616215

In [38]:
#위의 내용을 보면 알다시피 index가 아니다.
df.info() #DAte는 그냥 not-null object일 뿐이다. 즉 그냥 string 임

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 7 columns):
Date         1258 non-null object
Open         1258 non-null float64
High         1258 non-null float64
Low          1258 non-null float64
Close        1258 non-null float64
Volume       1258 non-null int64
Adj Close    1258 non-null float64
dtypes: float64(5), int64(1), object(1)
memory usage: 68.9+ KB

In [39]:
#import가 완료된 당므 python ㄹ에서 String인 Data type을 Datetime으로 변경
df['Date'] = pd.to_datetime(df['Date'])
#이미 데이터가 import 된 것에 대해 type을 변경 - 자주 씀

In [1]:
df.head()

NameError: name 'df' is not defined

In [41]:
df.info() # Date columens 의 date type,이 datetime64로 변경됨

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 7 columns):
Date         1258 non-null datetime64[ns]
Open         1258 non-null float64
High         1258 non-null float64
Low          1258 non-null float64
Close        1258 non-null float64
Volume       1258 non-null int64
Adj Close    1258 non-null float64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 68.9 KB

In [45]:
#date coulumn 을 index행으로 바꿔줌
df.set_index('Date', inplace=False) 
#Date 안에있는 값들이 굵게 표시 됨!

                 Open       High        Low      Close    Volume  Adj Close
Date
2012-01-03  59.970001  61.060001  59.869999  60.330002  12668800  52.619235
2012-01-04  60.209999  60.349998  59.470001  59.709999   9593300  52.078475
2012-01-05  59.349998  59.619999  58.369999  59.419998  12768200  51.825539
2012-01-06  59.419998  59.450001  58.869999  59.000000   8069400  51.459220
2012-01-09  59.029999  59.549999  58.919998  59.180000   6679300  51.616215
...               ...        ...        ...        ...       ...        ...
2016-12-23  69.430000  69.750000  69.360001  69.540001   4803900  69.032411
2016-12-27  69.300003  69.820000  69.250000  69.699997   4435700  69.191240
2016-12-28  69.940002  70.000000  69.260002  69.309998   4875700  68.804087
2016-12-29  69.209999  69.519997  69.120003  69.260002   4298400  68.754456
2016-12-30  69.120003  69.430000  68.830002  69.120003   6889500  68.615479

[1258 rows x 6 columns]

In [51]:
#짧게, 빠르게 세팅하는 방식
df = pd.read_csv('walmart_stock.csv', index_col = 'Date')
"""
상기했던 것들을 압축시키자면 위에처럼 하면 된다. 'Date column을ㅇ index
로 삼겠다고 지정. 하지만 여기서도 문제가 있음 index로 지정이 되었다하더라도
속성은 그대로 string 이다
'"""

"\n상기했던 것들을 압축시키자면 위에처럼 하면 된다. 'Date column을ㅇ index\n로 삼겠다고 지정. 하지만 여기서도 문제가 있음 index로 지정이 되었다하더라도\n속성은 그대로 string 이다\n'"

In [54]:
#짧지만 수정 못하는 방식
#parse_dates parameter는 index 지정은 물론 date를 datetime object로 
#pasing 하는 것 까지 시도해주는 고마운 parameter 이다.
#하지만 상세한 내용은 control 못하는다는 것이 함정

df = pd.read_csv('walmart_stock.csv', index_col='Date', parse_dates=True)

In [55]:
df.index
#정상적으로 적용되었는지 보기위함

DatetimeIndex(['2012-01-03', '2012-01-04', '2012-01-05', '2012-01-06',
               '2012-01-09', '2012-01-10', '2012-01-11', '2012-01-12',
               '2012-01-13', '2012-01-17',
               ...
               '2016-12-16', '2016-12-19', '2016-12-20', '2016-12-21',
               '2016-12-22', '2016-12-23', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', name='Date', length=1258, freq=None)

In [56]:
#혹은 아래 처럼
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex